version: "3.8"
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: inu
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: inu_db
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      - lava
      - db
    build: .
    restart: always
  lava:
    build: ./dependencies/fredboat/
    restart: always
    # image: fredboat/lavalink:master
    # configs:
    # - source: my_config
    #   target: /opt/Lavalink/application.yml
  # lava:
  #   build: dependencies/music/
configs:
  my_config:
    file: dependencies/fredboat/application.yml
