version: "3.8"
services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: inu
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: inu_db
      LOG_STATEMENT: WARNING
      LOG_LEVEL: INFO
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
  app:
    container_name: inu
    depends_on:
      - lava
      - db
    build: .
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # disable watchtower for this container
  lava:
    container_name: lavalink
    restart: "unless-stopped"
    image: fredboat/lavalink:3.7.8
    volumes:
      - ./dependencies/fredboat/application.yml:/opt/Lavalink/application.yml
configs:
  my_config:
    file: dependencies/fredboat/application.yml
