version: "3.8"
services:
  db:
    container_name: postgresql
    image: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: inu
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: inu_db
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
  app:
    container_name: inu
    depends_on:
      - lava
      - db
    build: .
    restart: "unless-stopped"
  lava:
    container_name: lavalink
    build: ./dependencies/fredboat/
    restart: "unless-stopped"
    # image: fredboat/lavalink:dev
    # configs:
    # - source: my_config
    #   target: /opt/Lavalink/application.yml
  # lava:
  #   build: dependencies/music/
configs:
  my_config:
    file: dependencies/fredboat/application.yml
