version: "3.8"
services:
  db:
    build: ./dependencies/postgres/
  app:
    depends_on:
#      - lava
      - db
    build: .
  # lava:
  #   image: fredboat/lavalink:master
  #   configs:
  #   - source: my_config
  #     target: /opt/Lavalink/application.yml
configs:
  my_config:
    file: /dependencies/fredboat/application.yml
