version: '3.8'  # Specify the version of the Docker Compose file

networks:
  inu_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16  # IPv4 subnet

services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: inu
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: inu_db
      LOG_STATEMENT: WARNING
      LOG_LEVEL: INFO
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
    networks:
      inu_net:  # Connect to the custom network

  app:
    container_name: inu
    depends_on:
      # - lava
      - db
    build: .
    restart: "unless-stopped"
    networks:
      inu_net:  # Connect to the custom network
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Disable watchtower for this container

  lava:
    container_name: lavalink
    restart: "unless-stopped"
    image: ghcr.io/lavalink-devs/lavalink:4
    volumes:
      - ./dependencies/lavalink/application.yml:/opt/Lavalink/application.yml
      - ./data/plugins/:/opt/Lavalink/plugins/
    networks:
      inu_net:  # Connect to the custom network