services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: inu
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: inu_db
      LOG_STATEMENT: WARNING
      LOG_LEVEL: INFO
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
  app:
    container_name: inu
    depends_on:
      - lava
      - db
    build: .
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # disable watchtower for this container
  lava:
    container_name: lavalink
    restart: "unless-stopped"
    image: fredboat/lavalink:4 #ghcr.io/lavalink-devs/lavalink:v3-update-lp-alpine #fredboat/lavalink:v3-update-lp-alpine
    volumes:
      - ./dependencies/lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      lavalink-net:
        ipv4_address: 192.168.100.10   # Static IPv4 address
        ipv6_address: 2001:db8:1::10   # Static IPv6 address

networks:
  lavalink-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
        - gateway: 192.168.100.1
        - subnet: 2001:db8:1::/64
        - gateway: 2001:db8:1::1