version: '3.8'  # Specify the version of the Docker Compose file

networks:
  inu_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16  # IPv4 subnet
        - subnet: "2001:db8:1::/64"  # IPv6 subnet

services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: inu
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: inu_db
      LOG_STATEMENT: WARNING
      LOG_LEVEL: INFO
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
    networks:
      inu_net:
        ipv4_address: 172.21.0.2  # Optional: assign a specific IPv4 address
        ipv6_address: "2001:db8:1::2"  # Optional: assign a specific IPv6 address

  app:
    container_name: inu
    depends_on:
      - lava
      - db
    build: .
    restart: "unless-stopped"
    environment:
      # Lavalink host can be accessed via its service name in the Docker network
      LAVALINK_HOST: "lava"  # Use the service name here
      LAVALINK_PORT: 2333
    networks:
      inu_net:
        ipv4_address: 172.21.0.3  # Assign a specific IPv4 address
        ipv6_address: "2001:db8:1::3"  # Assign a specific IPv6 address
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # disable watchtower for this container

  lava:
    container_name: lavalink
    restart: "unless-stopped"
    image: fredboat/lavalink:4
    volumes:
      - ./dependencies/lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      inu_net:
        ipv4_address: 172.21.0.4  # Assign a specific IPv4 address
        ipv6_address: "2001:db8:1::4"  # Assign a specific IPv6 address
