version: "3.8"
services:
  db:
    container_name: postgresql
    image: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: inu
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: inu_db
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
  app:
    container_name: inu
    depends_on:
      - lava
      - db
    build: .
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # disable watchtower for this container
  lava:
    container_name: lavalink
    restart: "unless-stopped"
    image: fredboat/lavalink:master
    volumes:
      - ./dependencies/fredboat/application.yml:/opt/Lavalink/application.yml
      #- target: /opt/Lavalink/application.yml
      # build: ./dependencies/fredboat/
configs:
  my_config:
    file: dependencies/fredboat/application.yml
