##############################################################
######################## USER SETTINGS #######################
##############################################################

bot:
    # ESSENTIAL! 
    # get it from https://discord.com/developers/applications -> your app -> bot -> token
    DISCORD_TOKEN: XXX  

    owner_id: 000       
    bug_channel_id: 000
    DEFAULT_PREFIX: inu.  # for message commands; will be deprecated
    SPECIAL_ROLE_NAME: Inu.  # name for a rule which gives users more privileges
    reboot: True  # whether to restart the bot when it crashes
    color: "475ad3"  # color used for some embeds
    guild_invite_url: "https://discord.gg/XXXXXXX"  # guild URL, when Error occurs where to get help
    domain: "example-domain.org"  # just displayed in the /ping command; not needed

# Rapid API for /urban
# get it from https://rapidapi.com/community/api/urban-dictionary
rapid:
    SECRET: XXX

# MyAnimeList for /anime, /anime-of-the-week
# get it from https://myanimelist.net/apiconfig -> Create ID
mal:
    ID: XXX
    SECRET: XXX

# Reddit for /anime-of-the-week
reddit:
    ID: XXX
    SECRET: XXX

# watch2gether for /watch2gether
w2g:
    ID: XXX
    API_URL: "https://api.w2g.tv"
    default_links:
        - "https://www.youtube.com/watch?v=Csek1JC4JzE" # satisfactory dev music
        # - "https://www.youtube.com/watch?v=x-Si5PfCgrs" # fairy fountain
        - "https://www.youtube.com/watch?v=xh_r_lEPfZ8" # dark world - zelda

# for /movie and /tv-show
tmdb:
    SECRET: XXX

# currently not used
spotify:
    ID: XXX
    SECRET: XXX

##############################################################
######################## DEV SETTINGS ########################
##############################################################
commands:
    board_entry_lifetime: 30 # days
    purge_limit: 50 # messages
    poll_sync_time: 300 # seconds
    anime_corner_sync_time: 6 # hours
    board_sync_time: 24 # hours

logging:
    # global will be overwritten from more specified ones
    # specify with __name__ or __name__ . func.__name__
    global: DEBUG
    core: DEBUG
    core.bot.Inu: DEBUG
    ext: DEBUG
    ext.commands.music: INFO
    utils: DEBUG
    core.context: INFO
    ext.commands.stats: INFO
    ext.tasks.reddit_post: INFO
    ext.commands.polls: INFO
    ext.commands.reddit: INFO
    ext.tasks: INFO
    utils.paginators: INFO
    utils.paginators.anime_pag: INFO
    hikari: INFO
    lightbulb: DEBUG
    colorlog: INFO

db:
    SQL_logging: False
    # for Docker
    DSN: postgresql://inu:secr33t@db/inu_db

lavalink:
    connect: True
    PASSWORD: youshallnotpass
    # for Docker (name of toplevel folder has to be `inu`)
    IP: lavalink
    # for localhost
    # IP: 127.0.0.1

tags:
    # between 0 and 1
    prediction_accuracy: 0.1

docker:
    PROJECT_NAME: inu

